version: '3.8'

services:
  app:
    build: .
    container_name: myapp
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-network
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  app-network:
